# Build stage
FROM gradle:jdk21 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle :bootstrap:api:bootJar --no-daemon

# Package stage
FROM openjdk:21
COPY --from=build /home/gradle/src/bootstrap/api/build/libs/api-*.jar /app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
