auth:
  token-secret: ${TOKEN_SECRET:secret}
  auth-code-expiration-seconds: ${AUTH_CODE_EXPIRATION_SECONDS:300}             # 5 minutes
  access-token-expiration-seconds: ${ACCESS_TOKEN_EXPIRATION_SECONDS:7200}      # 2 hours
  refresh-token-expiration-seconds: ${REFRESH_TOKEN_EXPIRATION_SECONDS:604800}  # 1 week
  register-token-expiration-seconds: ${REGISTER_TOKEN_EXPIRATION_SECONDS:86400} # 1 day
