spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
discord:
  auth-sms-hook-url: ${DISCORD_AUTH_SMS_HOOK_URL}
---
spring:
  config:
    activate:
      on-profile: prod
