spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/3days?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: secret
  flyway:
    enabled: true
    locations: classpath:db/migration
